/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gSaxAD8VNvI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Gabarito } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import styles from './styles.module.css';

export function MyHomePage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="size-6" />
          <span className="sr-only">Hyeji Chang's Portfolio</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Projects
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="hero" className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="container space-y-10 xl:space-y-16 px-4 md:px-6">
            <div className="grid gap-4 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Hyeji Chang
                </h1>
                <h2 className="text-2xl font-bold text-muted-foreground">Software Engineer</h2>
                <div className="mt text-muted-foreground"> born2slayy77@gmail.com</div>
                <div className="mt-4 flex items-center gap-4">
                  <Link
                    href="https://github.com/born2slayy"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <GithubIcon className="w-4 h-4 mr-2" />
                    GitHub
                  </Link>
                  <Link
                    href="https://github.com/born2slayy"
                    className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <LinkedinIcon className="w-4 h-4 mr-2" />
                    LinkedIn
                  </Link>
                </div>
                <p className="mt-4 max-w-[700px] text-muted-foreground md:text-xl">
                  Passionate software engineer with expertise in building scalable and innovative web applications.
                  Dedicated to delivering high-quality solutions that drive business success.
                </p>
              </div>
              <img
                src="/hyeji.jpg"
                width="450"
                height="450"
                alt="Hyeji Chang"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover rounded-circle"
              />
              <p></p>
            </div>
          </div>
        </section>
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Projects</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore a selection of my most recent and impactful projects.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              <Link href="https://www.youtube.com/watch?v=Ju2dxLSuEXI" prefetch={false}>
                <Card className="h-full">
                  <CardHeader>
                    <img
                      src="/rendi.png"
                      width="550"
                      height="310"
                      alt="Project 1"
                      className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    />
                  </CardHeader>
                  <CardContent>
                    <CardTitle>RENDI / LOOGLE</CardTitle>
                    <CardDescription>
                      AI search focused shopping platform, enabling nuancedtext, sentence, and image searches. Analyzed product images to extract nuances and keywords, storing the results for enhancing search capabilities. Implemented a search algorithm that calculates similarity scores between user queries and analyzed product data, presenting results in order of relevance 
                    </CardDescription>
                  </CardContent>
                </Card>
              </Link>
              <Link href="#" prefetch={false}>
                <Card className="h-full">
                  <CardHeader>
                    <img
                      src="/fusion.png"
                      width="550"
                      height="310"
                      alt="Project 2"
                      className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    />
                  </CardHeader>
                  <CardContent>
                    <CardTitle>Camera & 3D LiDAR SensorFusion</CardTitle>
                    <CardDescription>
                      Conducted sensor fusion between a 32‑channel 3D LiDAR and camera, aligning coordinates through camera intrinsic calibration and both extrinsic calibrations. Implemented cross‑projection techniques to integrate data from both sensors for improved object detection
                    </CardDescription>
                  </CardContent>
                </Card>
              </Link>
              <Link href="#" prefetch={false}>
                <Card className="h-full">
                  <CardHeader>
                    <img
                      src="/buildup.png"
                      width="550"
                      height="310"
                      alt="Project 3"
                      className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    />
                  </CardHeader>
                  <CardContent>
                    <CardTitle>Build Up</CardTitle>
                    <CardDescription>
                    Developed a record‑keeping application that allows users to document their school and extracurricular activities in detail, facilitating the creation of portfolios and resumes.Implemented career recommendation services and coffee chat features connecting users with senior peers based on recorded activities.
                    </CardDescription>
                  </CardContent>
                </Card>
              </Link>
              <Link href="#" prefetch={false}>
                <Card className="h-full">
                  <CardHeader>
                    <img
                      src="/lane.png"
                      width="550"
                      height="310"
                      alt="Project 4"
                      className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    />
                  </CardHeader>
                  <CardContent>
                    <CardTitle>Lane Detection</CardTitle>
                    <CardDescription>
                    Enhanced the Ultra Fast LaneNet model for lane detection, improving its recognition accuracy through additional computer vision processing techniques. 
                    Applied regression lines to detected lane points to filter out outliers with excessive curvature or variance, ensuring only accurately recognized lanes were retained. Calculated the difference between the median of lanes and the median of pixels, applying a low‑pass filter (LPF) to smooth the output. Published vehicle angle values using PID control through the Robot Operating System (ROS) for effective steering adjustments.
                    </CardDescription>
                  </CardContent>
                </Card>
              </Link>
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Me</h2>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I am a passionate and experienced software engineer with a strong background in full-stack web
                development. I have a proven track record of delivering high-quality, scalable applications that solve
                complex business problems.
              </p>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                My expertise spans a wide range of technologies, including React, Node.js, SQL, and cloud platforms. I
                am constantly learning and staying up-to-date with the latest industry trends and best practices to
                ensure I provide the most effective solutions for my clients.
              </p>
            </div>
            <div className="flex flex-col gap-4">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Skills</h2>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Back-end</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">Spring</Badge>
                  <Badge variant="secondary">Flask</Badge>
                  <Badge variant="secondary">Node.js</Badge>
                  <Badge variant="secondary">REST API</Badge>
                  <Badge variant="secondary">FAST API</Badge>
                </div>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Front-end</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">React</Badge>
                  <Badge variant="secondary">Next.js</Badge>
                  <Badge variant="secondary">Android</Badge>
                </div>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">DevOps</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">AWS</Badge>
                  <Badge variant="secondary">Docker</Badge>
                </div>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Deep Learning</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">Pytorch</Badge>
                  <Badge variant="secondary">Tensorflow</Badge>
                  <Badge variant="secondary">Keras</Badge>
                </div>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Programming</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">Python</Badge>
                  <Badge variant="secondary">C++</Badge>
                  <Badge variant="secondary">Java</Badge>
                </div>
              </div>
              {/* <div className="grid gap-1">
                <h3 className="text-xl font-bold">Experience</h3>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">5+ years of web development</Badge>
                  <Badge variant="secondary">Worked at leading tech companies</Badge>
                  <Badge variant="secondary">Delivered 20+ successful projects</Badge>
                </div>
              </div> */}
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Awards</h2>
              <div className="grid gap-1">
                <div className="flex flex-wrap gap-2">
                  <Badge variant="secondary">2023 ExcellenceAward, Undergraduate Paper Competition at the Korean MultimediaSociety Fall Conference</Badge>
                  <Badge variant="secondary"> 2023 GrandPrize, Uni‑Dthon Hackathon by University Union</Badge>
                  <Badge variant="secondary"> 2023 ParticipationAward, Autonomous Driving Software Advancement Competition</Badge>
                  <Badge variant="secondary"> 2023 EncouragementAward, IPS Hackathon</Badge>
                  <Badge variant="secondary"> 2022 Innovative Award, Uni‑Dthon Data Challenge by University Union</Badge>
                  <Badge variant="secondary">  2022 Excellence Award, Big Data Hackathon by Big Data Innovation Sharing University Project</Badge>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <div className="container max-w-7xl flex flex-col gap-4 sm:flex-row sm:justify-between">
          <p className="text-xs text-muted-foreground">&copy; 2024 Hyeji Chang. All rights reserved.</p>
          <nav className="flex gap-4 sm:gap-6">
            <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Privacy Policy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
